---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fedora-demo-snapshot
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/part-of: volume-restore-overrides-demo
    demo.phase: snapshot
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: vm-volume-restore-demo
  source:
    repoURL: https://github.com/awez-sonde/vm-volumerestoreoverrides.git
    targetRevision: main
    path: .
    directory:
      include: snapshot.yaml
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
