apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
namespace: vm-volume-restore-demo
patches:
  - target:
      kind: Namespace
      name: vm-demo
    patch: |-
      - op: replace
        path: /metadata/name
        value: vm-volume-restore-demo
